export const chainFixtures = [
  {
    name: "Arbitrum One",
    shortName: "arb1",
    infoUrl: "https://arbitrum.io",
    layer: "L2",
    interface: "evm",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 42161,
    networkSpec: 42161,
    parentChainSpec: 1,
    explorers: [
      {
        name: "Arbiscan",
        url: "https://arbiscan.io",
        spec: "eip3091",
      },
      {
        name: "Arbitrum Explorer",
        url: "https://explorer.arbitrum.io",
        spec: "eip3091",
      },
      {
        name: "dexguru",
        url: "https://arbitrum.dex.guru",
        icon: "dexguru",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Base",
    shortName: "base",
    infoUrl: "https://base.org",
    layer: "L2",
    interface: "evm",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 8453,
    networkSpec: 8453,
    parentChainSpec: 1,
    explorers: [
      { name: "basescan", url: "https://basescan.org", standard: "none" },
      {
        name: "basescout",
        url: "https://base.blockscout.com",
        icon: "blockscout",
        spec: "eip3091",
      },
      {
        name: "dexguru",
        url: "https://base.dex.guru",
        icon: "dexguru",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Blast",
    shortName: "blastmainnet",
    infoUrl: "https://blast.io/",
    layer: "L2",
    interface: "evm",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 81457,
    networkSpec: 81457,
    parentChainSpec: 1,
    explorers: [
      {
        name: "Blastscan",
        url: "https://blastscan.io",
        icon: "blast",
        spec: "eip3091",
      },
      {
        name: "Blast Explorer",
        url: "https://blastexplorer.io",
        icon: "blast",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Ethereum Mainnet",
    shortName: "eth",
    infoUrl: "https://ethereum.org",
    layer: "L1",
    interface: "evm",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 1,
    networkSpec: 1,
    slipSpec: 60,
    ensRegistry: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
    explorers: [
      {
        name: "etherscan",
        url: "https://etherscan.io",
        spec: "eip3091",
      },
      {
        name: "blockscout",
        url: "https://eth.blockscout.com",
        icon: "blockscout",
        spec: "eip3091",
      },
      {
        name: "dexguru",
        url: "https://ethereum.dex.guru",
        icon: "dexguru",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Linea",
    shortName: "linea",
    infoUrl: "https://linea.build",
    layer: "L2",
    interface: "evm",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: {
      name: "Linea Ether",
      symbol: "ETH",
      decimals: 18,
    },
    chainSpec: 59144,
    networkSpec: 59144,
    parentChainSpec: 1,
    explorers: [
      {
        name: "Etherscan",
        url: "https://lineascan.build",
        standard: "eip3091",
        icon: "linea",
      },
      {
        name: "Blockscout",
        url: "https://explorer.linea.build",
        standard: "eip3091",
        icon: "linea",
      },
      {
        name: "L2scan",
        url: "https://linea.l2scan.co",
        standard: "eip3091",
        icon: "linea",
      },
    ],
  },
  {
    name: "Mantle",
    shortName: "mantle",
    infoUrl: "https://mantle.xyz",
    interface: "evm",
    layer: "L2",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Mantle", symbol: "MNT", decimals: 18 },
    chainSpec: 5000,
    networkSpec: 5000,
    parentChainSpec: 1,
    explorers: [
      {
        name: "Mantle Explorer",
        url: "https://explorer.mantle.xyz",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "OP Mainnet",
    shortName: "oeth",
    infoUrl: "https://optimism.io",
    interface: "evm",
    layer: "L2",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 10,
    networkSpec: 10,
    parentChainSpec: 1,
    explorers: [
      {
        name: "etherscan",
        url: "https://optimistic.etherscan.io",
        spec: "eip3091",
      },
      {
        name: "blockscout",
        url: "https://optimism.blockscout.com",
        icon: "blockscout",
        spec: "eip3091",
      },
      {
        name: "dexguru",
        url: "https://optimism.dex.guru",
        icon: "dexguru",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Polygon Mainnet",
    shortName: "matic",
    infoUrl: "https://polygon.technology/",
    interface: "evm",
    layer: "L2",
    chainSpec: 137,
    networkSpec: 137,
    slip_id: 966,
    ecosystem: { name: "Polygon", ticker: "MATIC" },
    nativeCoin: { name: "MATIC", symbol: "MATIC", decimals: 18 },
    explorers: [
      {
        name: "polygonscan",
        url: "https://polygonscan.com",
        spec: "eip3091",
      },
      {
        name: "dexguru",
        url: "https://polygon.dex.guru",
        icon: "dexguru",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "Scroll",
    shortName: "scr",
    infoUrl: "https://scroll.io",
    interface: "evm",
    layer: "L2",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 534352,
    networkSpec: 534352,
    parentChainSpec: 1,
    explorers: [
      {
        name: "Scrollscan",
        url: "https://scrollscan.com",
        spec: "eip3091",
      },
      {
        name: "Blockscout",
        url: "https://blockscout.scroll.io",
        spec: "eip3091",
      },
    ],
  },
  {
    name: "zkSync Mainnet",
    shortName: "zksync",
    infoUrl: "https://zksync.io/",
    interface: "evm",
    layer: "L2",
    ecosystem: { name: "Ethereum", ticker: "evm" },
    nativeCoin: { name: "Ether", symbol: "ETH", decimals: 18 },
    chainSpec: 324,
    networkSpec: 324,
    parentChainSpec: 1,
    explorers: [
      {
        name: "zkSync Era Block Explorer",
        url: "https://explorer.zksync.io",
        icon: "zksync-era",
        spec: "eip3091",
      },
    ],
  },
];
